name = "glyn"
version = "2.0.3"
description = "Type-safe PubSub and Registry for Gleam actors with distributed clustering support"

licences = ["MIT"]
repository = { type = "github", user = "mbuhot", repo = "glyn" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
syn = ">= 3.3.0 and < 4.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleam_json = ">= 3.0.2 and < 4.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
