name = "glyn"
version = "1.0.0"

licences = ["MIT"]
repository = { type = "github", user = "mbuhot", repo = "glyn" }
links = [
  { title = "Repository", href = "https://github.com/mbuhot/glyn" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
syn = ">= 3.3.0 and < 4.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
